### ISSUE TITLE
Unable to resolve extended types

### ISSUE THREAD

**Issue by muhyousufmemon** [curioswitch/protobuf-jackson#10]
I have a Error type message which has the following inheritance structure

```
Error extends GeneratedMessageV3 implements ErrorOrBuilder
GeneratedMessageV3 extends AbstractMessage implements Serializable
AbstractMessage extends AbstractMessageLite implements Message
```
The ide throws `Error cannot resolve method `register(Error``

Does the library support GeneratedMessageV3? My initial thought was that it would support it since its expecting Message at the end of the day.

Thanks for the help

**Comment by chokoswitch** [comment]
Hi @muhyousufmemon

I looked at the generated source for the protos we use in the test and they are indeed `GeneratedMessageV3`, for example

```java
  public static final class TestAllTypes extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:json_test.TestAllTypes)
      TestAllTypesOrBuilder
```

so I think it should work.

It looks like your error message got cut off, can you provide the whole stack trace? Also it would be good to see the proto file  for that type as well and the version of protoc and protobuf-java you are using.

**Comment by muhyousufmemon** [comment]
Sorry about that. The protobuf resources were being shaded at some point. Thanks for the response though :)
