### ISSUE TITLE
Does this library support incremental registration of Message types?

### ISSUE THREAD

**Issue by muhyousufmemon** [curioswitch/protobuf-jackson#12]
We have a growing schema repo used by consumers. We have our server-side that processes these messages. 

I was wondering if we can register message types to marshaller incrementally as we receive request on the server-side for that particular message type. Any ideas?

**Comment by chokoswitch** [comment]
That's an interesting use case. The solution with the current version would be to reuse `MessageMarshaller.Builder`, but this means all messages are bytecode regenerated every time `build()` is called. It'll have cost, but I wonder how often such updates happen in terms of whether this cost is prohibitive.

A quick reasoning makes me think that `MessageMarshaller.toBuilder()` could be reasonable, it would create a builder but prepopulate `builtParsers` with what's already been generated. IIUC, this should basically work - one issue could be if a new message is added that has a dependency on a message with a different version, then `build()` would probably cause a linkage error - this would happen with just normal Java code too though I guess. 

Just to clarify, does your system dynamically add new message classes to the same classloader over time? If so, I guess if there is a compatibility problem this step itself would have an error, and on the flip side if it works, then `MessageMarshaller.toBuilder()` type of technique should work fine. This does seem to be a very unique use case though, I want to confirm that the cost of reusing the Builder would be prohibitive before adding a new API for it.

**Comment by chokoswitch** [comment]
Sorry rereading the comment, I think I missed the point. I guess you have a large schema, and instead of precompiling all the bytecode even when much isn't used, you'd like to lazily compile it, probably to improve startup time in common usages. That seems reasonable, let me think a bit about it.

**Comment by muhyousufmemon** [comment]
Yes, basically lazy load classes as they arrive on the server-side.

**Comment by chokoswitch** [comment]
@muhyousufmemon Snapshots have been published with the change

https://github.com/curioswitch/protobuf-jackson/actions/runs/4816447500/jobs/8576108488

Is this something you would be able to try in your app before committing to a release?

**Comment by muhyousufmemon** [comment]
@chokoswitch I was able to test. It works as expected. Thanks again :)

**Comment by chokoswitch** [comment]
@muhyousufmemon Thanks for verifying - 2.1.0 has been released with this change.

**Comment by C0mbatwombat** [comment]
Thanks for this addition! Very useful for us too. Had another question, is it possible to register a custom typehandler for a specific message type? I couldn't find a way to do it, and if it is not possible would it be ok to add it?

**Comment by C0mbatwombat** [comment]
And hijacking the thread just in case you see this @chokoswitch . Is there a way to make the conversion strict? For instance MessageMarshaller.mergeValue() currently allows unpacking a json int into a string. I would prefer it to throw an exception.

So a json `{"val": 1000} `is unpacked without an exception into a `message ProtoMessage { val string = 1}`

**Comment by chokoswitch** [comment]
Hi @C0mbatwombat - what do you mean exactly by `custom typehandler`? Do you want to hand-write marshaling logic for particular submessages in a tree?

For storing int to string field, upstream also accepts it, it seems. I've added a test in #16.

This library is meant to be a replacement for upstream that uses Jackson and bytecode generation, so I'd generally like to avoid adding configuration knobs that aren't present upstream. Notably, if upstream were to add the feature later and the knob names differed, it could cause some confusion.

Would you be interested in filing an issue [upstream](https://github.com/protocolbuffers/protobuf) to see if they'd be interested in adding such a mode? If upstream also had it, I'd feel much more comfortable adding it here.

**Comment by C0mbatwombat** [comment]
Hi @chokoswitch , thanks a lot for the clear explanation. It makes a lot of sense. The suggestion is indeed about hand-writing marshaling logic. I am pretty sure upstream will never allow custom (de-)serialization, as it breaks wire compatibility and tons of other invariants that they assume. (Within an organization it is very useful to be able to change the json encoding however.)

I suppose it would be quite a big step for you to add something that does not follow upstream. So I suppose I will fork your code and add the small changes locally.

Thanks a lot for the great library!

**Comment by chokoswitch** [comment]
Thanks @C0mbatwombat - while core marshaling is meant to match upstream, this is a library meant to integrate well with Jackson. After thinking a bit, I realized that your request could be satisfied with optional integration with jackson-databind - basically any marshalers registered for types are consulted from the databind context first before falling back to the normal generated bytecode. 

I have started on a PR for that

https://github.com/curioswitch/protobuf-jackson/pull/17/files#diff-59643dec798eeb071947be7922d487414a29851ed6c6c837112cd094192ebc97R60

Would this approach solve your issue? There's no new API needed for this and it's just tighter integration with Jackson than currently provided, which would be a good improvement for this library I think.

**Comment by C0mbatwombat** [comment]
Hi @chokoswitch, thanks for the PR! Interesting approach, am I correct in understanding that it doesn't change the core marshaller but changes the entrypoint of (de)serialization to jackson? And that using this approach it is possible to pick a different marshaller? Nice approach! I will test but I think this is indeed an approach that would work for my usecase. 

One remaining question: would this approach work with the incremental registration feature that you've committed as part of this issue? Ie. is it possible to add an extra proto message while using the jackson-databind flow?

**Comment by C0mbatwombat** [comment]
Did a test, it works! I'll await whether you want to merge/release it. Thanks

**Comment by chokoswitch** [comment]
@C0mbatwombat Thanks for verifying! 2.2.0 has been released with the new feature.

**Comment by C0mbatwombat** [comment]
Thanks!

**Comment by C0mbatwombat** [comment]
I got it integrated and it works, thanks! 

Not urgent, but I couldn't get merging into a builder to work, either with a class definition or an existing object. I suppose builder-specific (de-)serializers would have to be added and registered in MessageMarshallerModule? I got it to work using a hack, but it's not as efficient of course.

**Comment by chokoswitch** [comment]
Hi @C0mbatwombat - could you provide an example of the code that isn't working. Ideally, a failing unit test we can add would be best. Thanks!

**Comment by chokoswitch** [comment]
@C0mbatwombat Ah I believe I understand the example. Does it mean we need to tweak the module settings

https://github.com/curioswitch/protobuf-jackson/blob/main/src/main/java/org/curioswitch/common/protobuf/json/MessageMarshallerModule.java#L56

to add something like

```
addDeserializer(
          (Class) prototype.newBuilderForType().getClass(), new MessageBuilderDeserializer<>(prototype, marshaller));
```

? If you want to try making the change and it works, happy to review a PR, otherwise it will take me a bit to get to it since a fairly busy for the next week or two.

**Comment by C0mbatwombat** [comment]
Yes, correct! I'm also quite busy these days, if I find time I will do a PR. Otherwise it can wait, not urgent for me.
