### ISSUE TITLE
Support printing default values for specific fields if includingDefaultValueFields=false

### ISSUE THREAD

**Issue by C0mbatwombat** [curioswitch/protobuf-jackson#27]
The upstream JsonPrinter supports printing default values for specific fields: 

```
 * Creates a new {@link Printer} that will also print default-valued fields if their
 * FieldDescriptors are found in the supplied set. Empty repeated fields and map fields will be
 * printed as well, if they match. The new Printer clones all other configurations from the
 * current {@link Printer}. Call includingDefaultValueFields() with no args to unconditionally
 * output all fields.
 */
com.google.protobuf.util.JsonFormat.Printer#includingDefaultValueFields(java.util.Set<com.google.protobuf.Descriptors.FieldDescriptor>)
```

Because of your fix #20, this is already possible for non-repeated primitive fields by adding `optional` to the field definition and setting the field explicitly. However for repeated fields, this is not possible and so I'm stuck. Would it be possible to add the upstream method to this project?

Again, thanks in advance!

**Comment by chokoswitch** [comment]
Hi @C0mbatwombat - I added the option in #29, can you confirm it satisfies your use case? Then I'll cut a release. Cheers.

**Comment by C0mbatwombat** [comment]
@chokoswitch Yes, perfect!

**Comment by chokoswitch** [comment]
Sorry for the long delay @C0mbatwombat, it looks like I had actually published a release but forgot to right release notes for it. And then ended up publishing the same again as 2.5.0 >< But it should be ready now.
