### ISSUE TITLE
Allow caching between multiple invocations of MessageMarshaller.builder().register(<type>)

### ISSUE THREAD

**Issue by C0mbatwombat** [curioswitch/protobuf-jackson#38]
Hi @chokoswitch :wave:,

I was doing some startup optimization work on our server, and it got me thinking whether it would be possible to make it an option to enable caching of creating `TypeSpecificMarshaller`s? 

To be precise, whether a static field similar to `private final Map<Descriptor, TypeSpecificMarshaller<?>> preBuiltParsers;`  could be added? Something like:
```java 

private static final Map<Descriptor, TypeSpecificMarshaller<?>> preBuiltParsersLibrary = new ConcurrentHashMap<>();

// usage something like, not 100% how the code structure should look
preBuiltParsersLibrary.computeIfAbsent(descriptor, descr -> buildMarshaller(prototype, includingDefaultValueFields
fieldsToAlwaysOutput, preservingProtoFieldNames, ignoringUnknownFields, printingEnumsAsInts, sortingMapKeys);
}
```

In our case we have multiple places where we create a `MessageMarshaller`, and we often register the same classes, or classes which have common fields, and I notice at startup we are generating TypeSpecificMarshallers for the same Descriptors multiple times. So a shared library would speed things up as ByteBuddy always takes some time.

Thanks!

**Comment by chokoswitch** [comment]
Hi @C0mbatwombat - sorry for the late response. Just to check, around how many `MessageMarshaller` instances do you have? And would you be able to give a try to a custom build you make with the static map to see how impactful it is on your startup time? I'd like to understand how significant the improvement could be.

The biggest issue is I think it's important for the generated marshallers to be GC'd when the `MessageMarshaller` is, they are scoped to it at least in terms of the API usage. I think this would still be possible with some reference-counting or weakmap approach though would be a bit nervous. I think it can be worth trying though if you see potential for a good speedup

**Comment by C0mbatwombat** [comment]
Hey @chokoswitch , no worries of course, thanks for the thoughtful reply. I understand the issues you see. I will try to do a test at some point (might take a while because I need to find some time). 

Another solution could be that a caller can provide a map that is then set in the `preBuiltParsers` variable? 

Something like
```java
Map<Descriptor, TypeSpecificMarshaller<?>> sharedMarshallers = new ConcurrentHashMap<>();
MessageMarshaller.builder(sharedMarshallers).register(<type>)..
```
If I make the `sharedMarshallers` a static field it could be reused across multiple builders. I'm not sure if it is a good idea in terms of how the API looks. And it does give the user a footgun which might not be the best idea.

Thanks!

**Comment by chokoswitch** [comment]
Thanks @C0mbatwombat - yeah additional API could be a way that is explicitly opt-in to the behavior, but as you say it's a bit of a tricky method, just in a general sense methods that accept a `Map` almost always copy from it rather than reuse it. So it would need careful naming / documentation.

A more automatic approach, if possible, would be better and I realized actually it shouldn't be too complex - I was thinking of needing to keep track of `MessageMarshaller`, but really just a weak map should work fine. Will play with the idea.

**Comment by chokoswitch** [comment]
@C0mbatwombat I implemented an automatic cache in #39. Could you give the snapshot a go? If you're able to do a bit of stress testing, that would be great as the change ended up a bit more complicated than I thought, especially the cache key being Descriptor+marshalling options, not just Descriptor. But if you're able to measure startup speed before and after, that would be really helpful!

**Comment by C0mbatwombat** [comment]
Hi @chokoswitch , sorry for the slow reply! I have tried it locally, and it works, but I can't really pin down whether I see a lot of speedup. Then again I have a hard time profiling it on my server. When I initially reported the issue I took some stacktraces and saw the ByteBuddy compiler often during startup, but again I have a hard time pinning it down. I do see the cache being hit but the startup takes around the same time as earlier. Sorry for the vague feedback.

Generally I think the change is nice and results in speedup, so it would be nice to keep it in!

**Comment by chokoswitch** [comment]
Thanks for verifying @C0mbatwombat I've gone ahead and released a new version with the change.

**Comment by chokoswitch** [comment]
Hi @C0mbatwombat - thanks for the report and sorry for the trouble. With my main language being Go lately it seems I accidentally only cut a tag without running the actual publishing workflow - very embarrassing 😅

I think it should be published now.

**Comment by C0mbatwombat** [comment]
Thanks!
